### ISSUE TITLE
no such file or directory for socket connect

### ISSUE THREAD

**Issue by Mr-Ples** [hyprland-community/hyprland-py#14]
```
[simon@socrates hyprland-py]$ python main.py
Traceback (most recent call last):
  File "/home/simon/scripts/python/hyprland-py/main.py", line 233, in <module>
    e.async_connect()
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/hyprland/event.py", line 28, in async_connect
    asyncio.run(_async_handler(self))
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/hyprland/event.py", line 20, in _async_handler
    await Dispatch.reload_config()
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/hyprland/dispatch.py", line 111, in reload_config
    await async_command_send('reload')
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/hyprland/sockets.py", line 20, in async_command_send
    reader, writer = await asyncio.open_unix_connection(f"/tmp/hypr/{os.getenv('HYPRLAND_INSTANCE_SIGNATURE')}/.socket.sock")
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/asyncio/streams.py", line 98, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/asyncio/unix_events.py", line 255, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
[simon@socrates hyprland-py]$ cat $HYPRLAND_INSTANCE_SIGNATURE
cat: a3b4923c4218535878dcf68d27d8eca4ab3e0981_1714784452_1702152959: No such file or directory
```

version: `hyprland           0.2.54`

**Comment by Mr-Ples** [comment]
probably related to recent change:
```
since https://github.com/hyprwm/Hyprland/commit/a5a648091760ac002120fab18247e5292b6482de 
the directory for sockets and logs has changed from /tmp/hypr/$HIS to $XDG_RUNTIME_DIR/hypr/$HIS, so you'll need to adjust your scripts if you listen to socket2, or read logs.
```

**Comment by Mr-Ples** [comment]
indeed after fixing the various lines in `socket.py` with the new path it works again. well doesn't crash dunno if that fixed everything there is to fix

**Comment by flickowoa** [comment]
it was fixed in a pr by @Evangelospro a few days ago, it should be fixed on the git version (ill update on pypi soon)
