### ISSUE TITLE
bs4 not listed as a dependency

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [hyprland-community/hyprland-py#2]
The module requires `bs4`, however it must have not been listed in your requirements.
```
Traceback (most recent call last):
  File "/home/zeb/.config/eww/scripts/firefox.py", line 1, in <module>
    import hyprland
  File "/home/zeb/.local/lib/python3.10/site-packages/hyprland/__init__.py", line 1, in <module>
    from .config import Config
  File "/home/zeb/.local/lib/python3.10/site-packages/hyprland/config.py", line 6, in <module>
    from .info import Info
  File "/home/zeb/.local/lib/python3.10/site-packages/hyprland/info.py", line 2, in <module>
    from .util.scraper import parse_val
  File "/home/zeb/.local/lib/python3.10/site-packages/hyprland/util/scraper.py", line 2, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'
```

**Comment by FoxNerdSaysMoo** [comment]
Same goes for `rich`
